sudo: false
language: rust
rust:
  - 1.18.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.8/libsodium-1.0.8.tar.gz &&
    tar xvfz libsodium-1.0.8.tar.gz &&
    cd libsodium-1.0.8 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
    cd ..
  - export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH &&
    export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
  - cargo install --force cargo-audit
script:
  - cargo build && cargo test
  - cargo audit
