[package]
name = "threema-gateway"
version = "0.2.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
documentation = "https://docs.rs/threema-gateway"
repository = "https://github.com/dbrgn/threema-gateway-rs"
license = "MIT OR Apache-2.0"
description = "A client library for the Threema Gateway."
readme = "README.md"
keywords = ["threema", "end-to-end", "e2e", "e2ee", "gateway"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[features]
dev = []

[dependencies]
hyper = "0.9"
url = "1.2.0"
sodiumoxide = "0.0.12"
data-encoding = "1.1"
quick-error = "1.1"

[dev-dependencies]
docopt = "0.6"
